"""Initial migration

Revision ID: 84907d38fe1a
Revises: 
Create Date: 2026-04-08 09:34:40.390903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84907d38fe1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create schema if it doesn't exist
    op.execute("CREATE SCHEMA IF NOT EXISTS sto_khnu")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sto_khnu'
    )
    op.create_index(op.f('ix_sto_khnu_clients_id'), 'clients', ['id'], unique=False, schema='sto_khnu')
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['sto_khnu.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sto_khnu'
    )
    op.create_index(op.f('ix_sto_khnu_vehicles_id'), 'vehicles', ['id'], unique=False, schema='sto_khnu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sto_khnu_vehicles_id'), table_name='vehicles', schema='sto_khnu')
    op.drop_table('vehicles', schema='sto_khnu')
    op.drop_index(op.f('ix_sto_khnu_clients_id'), table_name='clients', schema='sto_khnu')
    op.drop_table('clients', schema='sto_khnu')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS sto_khnu")
